### ISSUE TITLE
running in github actions

### ISSUE THREAD

**Issue by AntouanK** [silinternational/ecs-deploy#242]
hi there.

I'm running this in a github actions job, with the snippet given in the README

```
      - name: Deploy to Amazon ECS
        uses: silinternational/ecs-deploy@master
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
        with:
          aws_access_key_cmd: "--aws-access-key"
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key_cmd: "--aws-secret-key"
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          cluster_cmd: "--cluster"
          cluster: ${{ secrets.ECS_CLUSTER }}
          image_cmd: "--image"
          image: ${{ steps.build-image.outputs.image }}
          region_cmd: "--region"
          region: ${{ secrets.AWS_REGION }}
          service_name_cmd: "--service-name"
          service_name: ${{ secrets.ECS_SERVICE }}
          timeout_cmd: "--timeout"
          timeout: "360"
```

I get a `An error occurred (ClientException) when calling the DescribeTaskDefinition operation: Unable to describe task definition.` error.

I tried adding a 
```
          task_definition: "foo-bar"
```
in `with:` and then I get the command help output.

how do I run this to deploy the image I build with github actions?

thank you.
